<a href="https://colab.research.google.com/github/sndhanush99/DHV-LAB/blob/main/labsheet_4_20221COM0030.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3])
print(type(a), a.shape,a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [ ]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [ ]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e=np.random.random((2,2))
print(e)

[[0.57508168 0.37166968]
 [0.76310365 0.23999265]]


In [ ]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
b=a[:2, 1:3]
print(a)
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
print(a[0,1])
b[0,0] = 77
print(a[0,1])


2
77


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1=a[1, :]
row_r2=a[1:2, :]
row_r3=a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_r1=a[:, 1 ]
col_r2=a[:, 1:2 ]
col_r3=a[:, [1] ]
print(col_r1 , col_r1.shape)
print(col_r2 , col_r2.shape)
print(col_r3 , col_r3.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]
[1 4 5]


In [ ]:
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[2 2]
[2 2]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b=np.array([0,2,0,1])
print(a[np.arange(4),b])

[ 1  6  7 11]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
x=np.array([1,2])
y=np.array([1.0,2.0])
z=np.array([1,2],dtype=np.int64)
print(x.dtype,y.dtype,z.dtype)

int64 float64 int64


In [ ]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
x=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [ 8. 10.]]
[[ 6.  8.]
 [ 8. 10.]]


In [ ]:
print(x-y)
print(np.subtract(x,y))

[[4. 4.]
 [6. 6.]]
[[4. 4.]
 [6. 6.]]


In [ ]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [ 7. 16.]]
[[ 5. 12.]
 [ 7. 16.]]


In [ ]:
print(x/y)
print(np.divide(x,y))

[[5. 3.]
 [7. 4.]]
[[5. 3.]
 [7. 4.]]


In [ ]:
print(np.sqrt(x))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
v=np.array([9,10])
w=np.array([11,12])
print(v.dot(w))
print(np.dot(v,w))

219
219


In [ ]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [ ]:
print(v @ w)

219


In [ ]:
print(x.dot(v))
print(np.dot(x,v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
print( x @ y)

[[19 22]
 [43 50]]


In [ ]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [ ]:
x=np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x , axis=0))
print(np.sum(x , axis=1))

10
[4 6]
[3 7]
